name: CI & Docker Build + Push

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: ⬇️ Install pnpm
        run: npm install -g pnpm

      - name: 📦 Install monorepo dependencies
        run: pnpm install

      - name: 🔁 Generate Prisma client
        run: pnpm --filter db run generate

      - name: 🔨 Build server
        run: pnpm --filter server run build

      - name: 🐳 Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 🧱 Build Docker image from monorepo root
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/distributed-validator-sim:latest .

      - name: 🚀 Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/distributed-validator-sim:latest
